AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - lib/generators/**/*.rb
    - gemfiles/*
    - spec/**/*.rb

Documentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Naming/PredicateName:
  Enabled: false
