language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.1.gemfile
before_install:
  - gem update --system
  - gem install bundler
after_success:
  - bundle exec codeclimate-test-reporter
env:
  global:
    - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
