language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.0-rc2
  - 2.5.3
  - 2.4.5
  - 2.3.8
gemfile:
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.2.gemfile
before_install:
  - gem update --system
  - gem install bundler --no-document
after_success:
  - bundle exec codeclimate-test-reporter
env:
  global:
    - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
