language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
gemfile:
  - gemfiles/rails_4.2.10.gemfile
  - gemfiles/rails_5.0.6.gemfile
  - gemfiles/rails_5.1.5.gemfile
  - gemfiles/rails_5.2.0.rc1.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
env:
  global:
    - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
