language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
gemfile:
  - gemfiles/rails_4.2.8.gemfile
  - gemfiles/rails_5.0.3.gemfile
  - gemfiles/rails_5.1.1.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
env:
  global:
    - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
